// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_aVAzna-WllAe2W4Fnb-ssqpvzVx770E',
    appId: '1:486952228160:web:73902adb7b4260935816a5',
    messagingSenderId: '486952228160',
    projectId: 'fir-test-11f2d',
    authDomain: 'fir-test-11f2d.firebaseapp.com',
    storageBucket: 'fir-test-11f2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABKx7RAp2LSvJVgCZZDkWiGxizr6Fy8SI',
    appId: '1:486952228160:android:b9a36600893d60b15816a5',
    messagingSenderId: '486952228160',
    projectId: 'fir-test-11f2d',
    storageBucket: 'fir-test-11f2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8Jr9ZI0aceslMZXrBx4vqyUxUiPu7q-c',
    appId: '1:486952228160:ios:c45ed96fdcd5beb75816a5',
    messagingSenderId: '486952228160',
    projectId: 'fir-test-11f2d',
    storageBucket: 'fir-test-11f2d.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8Jr9ZI0aceslMZXrBx4vqyUxUiPu7q-c',
    appId: '1:486952228160:ios:c45ed96fdcd5beb75816a5',
    messagingSenderId: '486952228160',
    projectId: 'fir-test-11f2d',
    storageBucket: 'fir-test-11f2d.appspot.com',
    iosBundleId: 'com.example.untitled2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_aVAzna-WllAe2W4Fnb-ssqpvzVx770E',
    appId: '1:486952228160:web:0099e8f920ddbdbd5816a5',
    messagingSenderId: '486952228160',
    projectId: 'fir-test-11f2d',
    authDomain: 'fir-test-11f2d.firebaseapp.com',
    storageBucket: 'fir-test-11f2d.appspot.com',
  );
}
